// The workshop gantry: the floor splits open and robotic arms rise out of the pit,
// carrying armor plates, presenting them, pressing them home, releasing and withdrawing.
// Owned by task `suitup`. Used by the Mk I, Mk II and Mk III sequences.
//
// The model is models/gantry.glb (generated by models/gantry-build.py). It ships ONE
// arm prototype and this file clones it, so the number of arms is a gameplay decision.
// Segment lengths and joint axes are read out of the node tree at load time — the
// prototype deliberately runs its limbs along local +Y so that anything assuming -Y
// breaks loudly here rather than quietly in the armor.

import * as THREE from 'three';

const _v = new THREE.Vector3(), _v2 = new THREE.Vector3(), _q = new THREE.Quaternion();
const _m = new THREE.Matrix4();

// --------------------------------------------------------------------- stage lighting
//
// The workshop's own lighting is a dark room with cool strips in it, which is correct
// for the room and useless for the armour: rendered in it, a Mk III reads as a black
// silhouette with a white blob on its chest, and the gold never appears at all
// (measured — shots/suitup/P_pose_stand.png, first pass).
//
// Every reference frame of a suit-up is the same picture: the SUIT is lit hard and
// everything behind it falls to near black (reference/suitup/mk4_stage_gantry.jpg,
// gantry_mk3_construction_pair.jpg). That is not ambient light, it is a three-light
// stage rig aimed at the pad — key, cool rim, warm kicker — and it belongs to the
// ritual, not to the room. So the suit-up brings its own lights and takes them away
// again when it is finished.
//
// Intensities are in the renderer's physical units, the same scale env.js uses (its sun
// is 2.3 irradiance). A spot delivers I / d², so a key 3.9 m out at intensity 55 lands
// about 3.6 on the chest: brighter than the sun at noon, which is the point — this is a
// hard studio key in a black room, and it clips the gold to a specular sweep rather than
// lifting the whole scene.
export class SuitStage {
  constructor(ctx) {
    this.ctx = ctx;
    this.level = 0;
    this.target = 0;
    this.group = new THREE.Group();
    this.group.name = 'suitup_stage';
    this.group.visible = false;

    const spot = (color, intensity, pos, angle, penumbra) => {
      const l = new THREE.SpotLight(color, 0, 14, angle, penumbra, 2.0);
      l.position.set(pos[0], pos[1], pos[2]);
      l.target.position.set(0, 1.15, 0);
      l.userData.full = intensity;
      this.group.add(l);
      this.group.add(l.target);
      return l;
    };
    // Front-left and high: the key. It is the one that has to make lacquer look wet.
    // Cones are kept tight on purpose: the workshop has fog in it, and a wide spot pours
    // most of its light into the haze and onto the floor instead of onto the suit.
    this.key = spot(0xeaf3ff, 82, [1.85, 3.30, -2.45], 0.50, 0.45);
    this.key.castShadow = true;
    this.key.shadow.mapSize.set(1024, 1024);
    this.key.shadow.bias = -0.0015;
    this.key.shadow.camera.near = 0.5;
    this.key.shadow.camera.far = 12;
    // Behind and to the right: the cool rim that cuts the silhouette out of the black.
    this.rim = spot(0xa8c8ff, 74, [-2.15, 2.70, 2.55], 0.46, 0.60);
    // Low warm kicker on the far side — this is the light the open floor is supposed to
    // be throwing up at him. Aimed at the CHEST and kept narrow: at pit level with a
    // 40-degree cone it lit two square metres of floor instead, and through the
    // workshop's fog that read as a headlight parked next to him
    // (shots/suitup/P_pose_stand.png, third pass).
    this.kick = spot(0xffcf9a, 19, [2.30, 1.05, 1.85], 0.42, 0.75);
    this.kick.target.position.set(0, 1.45, 0);
    this.lights = [this.key, this.rim, this.kick];
    this.exposure = 1;

    ctx.scene.add(this.group);
  }

  // One key does not suit five surfaces. Pitted steel eats light; champagne gold throws
  // most of it straight back and blows to white under the same lamp (measured —
  // shots/suitup/F_mk42_closed.png, third pass, a Mk XLII with no readable face left).
  // This is the gaffer's knob, not a per-armor lighting rig: same three lamps, trimmed.
  forArmor(id) {
    // Re-trimmed after the key and rim were raised to beat the workshop's own light:
    // at the old numbers the Mk L rendered as a white shirt and a white face with the
    // burgundy gone (probe X_nano_18/44), which is the exact failure the reference warns
    // about — a suit lit uniformly and blown out reads as plastic.
    // Halving these again did NOT rescue the Mk XLII helmet close-up — that frame is
    // specular, not exposure (see GLOW_LEVEL in suit.js) — so they stay where the shipped
    // frames were shot. Pitted steel still needs three times what the gold does.
    this.exposure = { mk1: 1.00, mk2: 0.54, mk3: 0.66, mk42: 0.32, mk50: 0.52 }[id] || 0.7;
    this._apply();
  }

  place(pos, yaw = 0) {
    this.group.position.copy(pos);
    this.group.rotation.set(0, yaw, 0);
  }

  set(v) { this.target = THREE.MathUtils.clamp(v, 0, 1); }

  update(dt) {
    if (Math.abs(this.level - this.target) < 1e-3) {
      if (this.level !== this.target) { this.level = this.target; this._apply(); }
      return;
    }
    // Up fast (the rig strikes), down slow (it dims out behind him).
    const rate = this.target > this.level ? 1 / 0.55 : 1 / 1.9;
    const step = rate * dt;
    this.level += THREE.MathUtils.clamp(this.target - this.level, -step, step);
    this._apply();
  }

  _apply() {
    const k = this.level * this.level * (3 - 2 * this.level) * this.exposure;
    for (const l of this.lights) l.intensity = l.userData.full * k;
    // A spot at intensity 0 still costs every lit fragment a loop iteration, and this
    // rig is off for the whole rest of the game.
    this.group.visible = this.level > 0.002;
    this.key.castShadow = this.level > 0.35;
  }

  dispose() {
    if (this.group.parent) this.group.parent.remove(this.group);
  }
}

const HATCH_SLIDE = 1.62;   // metres each half travels
// How far an arm rises out of the pit. Raised from 1.55: with the shoulder at 0.72 m a
// single arm could not reach a chest or helmet plate on the far side of the body — it
// stretched flat and stopped 0.29-0.43 m short (probe X_mk1_t9, X_mk1_t125).
const RISE = 1.78;
// How high the arm bases stand ABOVE the pad once they are out. RISE only ever set how
// deep they sank; the shoulder stayed at 0.72 m and a single arm could not reach a helmet
// plate across the body (probe: err 0.31 m at t=12.5). Standing 0.24 m proud puts the
// shoulder at 0.96 m and every plate on the armour inside reach.
const ARM_STAND = 0.24;

class Arm {
  constructor(root, index) {
    this.root = root;          // the piv_arm_root of this clone
    this.index = index;
    this.parts = {};
    root.traverse(o => { if (o.name) this.parts[o.name.replace(/_\d+$/, '')] = o; });
    this.yaw = this.parts.piv_arm_yaw;
    this.shoulder = this.parts.piv_arm_shoulder;
    this.elbow = this.parts.piv_arm_elbow;
    this.wrist = this.parts.piv_arm_wrist;
    this.grip = this.parts.piv_arm_grip;
    this.jawL = this.parts.piv_arm_jawL;
    this.jawR = this.parts.piv_arm_jawR;

    // Derive the chain from the model. Never hard-code: models/gantry-build.py can
    // change the proportions and the IK has to follow.
    this.axisUpper = this.elbow ? this.elbow.position.clone().normalize() : new THREE.Vector3(0, 1, 0);
    this.L1 = this.elbow ? this.elbow.position.length() : 0.78;
    const wristLen = this.wrist ? this.wrist.position.length() : 0.62;
    const gripLen = this.grip ? this.grip.position.length() : 0.21;
    this.L2 = wristLen + gripLen;
    // Height of the shoulder above the arm root, on the yaw axis (invariant under yaw).
    this.baseY = (this.yaw ? this.yaw.position.y : 0.62) + (this.shoulder ? this.shoulder.position.y : 0.10);
    this.jaws = 0;             // 0 closed, 1 wide open
    this.holding = null;       // plate name, for bookkeeping
    this.reachError = 0;
  }

  // Put the GRIP POINT at a world position. Two-bone IK in the yaw plane; the numbers
  // come from the node tree, so this stays correct if the model is regenerated.
  reachTo(worldTarget) {
    const parent = this.root.parent;
    parent.updateWorldMatrix(true, false);
    _m.copy(this.root.matrixWorld).invert();
    const t = _v.copy(worldTarget).applyMatrix4(_m);   // arm-root local space

    const yaw = Math.atan2(t.x, t.z);
    if (this.yaw) this.yaw.rotation.set(0, yaw, 0);

    const d = Math.hypot(t.x, t.z);
    const h = t.y - this.baseY;
    const L1 = this.L1, L2 = this.L2;
    let r = Math.hypot(d, h);
    const rMin = Math.abs(L1 - L2) + 0.02, rMax = L1 + L2 - 0.02;
    this.reachError = r > rMax ? r - rMax : 0;
    r = THREE.MathUtils.clamp(r, rMin, rMax);

    const a = Math.atan2(d, h);                                    // target off the +Y axis
    const A = Math.acos(THREE.MathUtils.clamp((r * r + L1 * L1 - L2 * L2) / (2 * r * L1), -1, 1));
    const C = Math.acos(THREE.MathUtils.clamp((L1 * L1 + L2 * L2 - r * r) / (2 * L1 * L2), -1, 1));
    if (this.shoulder) this.shoulder.rotation.set(a - A, 0, 0);
    if (this.elbow) this.elbow.rotation.set(Math.PI - C, 0, 0);
    return this.reachError;
  }

  // Point the wrist so a held plate faces along `normal` (world) — the plate is
  // presented face-out, the way a claw holds a shell it is about to press on.
  faceAlong(worldNormal) {
    if (!this.wrist) return;
    this.wrist.parent.updateWorldMatrix(true, false);
    _q.copy(this.wrist.parent.getWorldQuaternion(new THREE.Quaternion())).invert();
    const local = _v2.copy(worldNormal).applyQuaternion(_q).normalize();
    const rest = new THREE.Vector3(0, 1, 0);
    this.wrist.quaternion.setFromUnitVectors(rest, local);
  }

  setJaws(f) {
    this.jaws = f;
    const a = THREE.MathUtils.degToRad(34) * f;
    if (this.jawL) this.jawL.rotation.set(0, 0, a);
    if (this.jawR) this.jawR.rotation.set(0, 0, -a);
  }

  // Where this arm has a plate waiting for it: a point just out of the pit, on the
  // arm's OWN side of the pad, between its base and the boy.
  //
  // It has to be derived from the arm's WORLD position. The sequences used to build it
  // as `padWorld + armHome`, mixing a world point with a gantry-LOCAL offset: at the
  // workshop pad the boy stands yawed about half a turn, so the pick-up point landed on
  // the far side of his body from the arm that wanted it. The arm then stretched flat
  // out and stopped 0.71 m short every single time (measured, probe X_mk1_t34), which is
  // why frames of the Mk I ritual had plates floating onto him with no machine anywhere
  // near them.
  pitPoint(padWorld, out) {
    this.root.getWorldPosition(out);
    out.lerp(padWorld, 0.40);
    out.y = padWorld.y + 0.07;
    return out;
  }

  // A parking pose out of the way: up, out, and on its own side.
  idlePoint(padWorld, out, spread = 1.0, height = 1.25) {
    this.root.getWorldPosition(out);
    out.sub(padWorld).multiplyScalar(spread).add(padWorld);
    out.y = padWorld.y + height;
    return out;
  }

  gripWorld(out) {
    if (!this.grip) return out.copy(this.root.getWorldPosition(_v));
    this.grip.updateWorldMatrix(true, false);
    return out.setFromMatrixPosition(this.grip.matrixWorld);
  }

  // Park position inside the pit: folded, pointing straight up, below the floor.
  fold() {
    if (this.yaw) this.yaw.rotation.set(0, 0, 0);
    if (this.shoulder) this.shoulder.rotation.set(0.18, 0, 0);
    if (this.elbow) this.elbow.rotation.set(2.35, 0, 0);
    if (this.wrist) this.wrist.quaternion.identity();
  }
}

export class Gantry {
  constructor(ctx, scene3) {
    this.ctx = ctx;
    this.group = new THREE.Group();
    this.group.name = 'gantry';
    this.group.visible = false;
    this.arms = [];
    this.hatchL = null;
    this.hatchR = null;
    this.deployT = 0;          // 0 stowed, 1 fully deployed
    this.armRaise = [1, 1, 1, 1];   // per-arm, multiplied by the deploy (see setArmRaise)
    this._rise = 0;
    this._built = false;
    this._src = scene3;
  }

  static async create(ctx) {
    let scene3 = null;
    try {
      const gltf = await ctx.assets.loadModel('models/gantry.glb');
      if (gltf && gltf.scene) scene3 = gltf.scene;
    } catch (e) { /* fall through to the procedural stand-in */ }
    const g = new Gantry(ctx, scene3);
    g.build();
    ctx.scene.add(g.group);
    return g;
  }

  build() {
    if (this._built) return;
    this._built = true;
    const src = this._src ? this._src.clone(true) : buildFallbackGantry();

    const byName = new Map();
    src.traverse(o => { if (o.name) byName.set(o.name, o); });
    this.hatchL = byName.get('hatchL');
    this.hatchR = byName.get('hatchR');
    const proto = byName.get('arm_proto') || byName.get('piv_arm_root');

    // Verify the exported node tree rather than trusting it (ARCHITECTURE.md).
    const need = ['piv_arm_root', 'piv_arm_yaw', 'piv_arm_shoulder', 'piv_arm_elbow',
      'piv_arm_wrist', 'piv_arm_grip'];
    const missing = need.filter(n => !byName.has(n));
    if (missing.length) console.warn('[gantry] model is missing', missing.join(' '));
    if (!this.hatchL || !this.hatchR) console.warn('[gantry] model has no hatch halves');

    // The game decides emission here too. A glow strip authored at 4.5 turns into a
    // floodlight once the bloom pass sees it, and the machinery must never outshine the
    // armour it is bolting on — reference/suitup/mk4_stage_gantry.jpg is a dark stage with
    // a cool strip in it, not a lightbox.
    src.traverse(o => {
      if (!o.isMesh) return;
      const mats = Array.isArray(o.material) ? o.material : [o.material];
      for (const m of mats) {
        if (!m || !m.emissive) continue;
        if (m.emissive.r + m.emissive.g + m.emissive.b < 0.02) continue;
        // 1.1 is still above the bloom threshold (1.05), so every strip on every segment
        // blew to a white blob and four arms turned the workshop into a chandelier
        // (shots/suitup/S_mk1_32.png). The machinery must never outshine the armour it
        // is bolting on: strips read as strips, and the reactor stays the brightest
        // thing in the room.
        m.emissiveIntensity = Math.min(m.emissiveIntensity || 1, 0.34);
        m.toneMapped = false;
      }
      // ...and the game decides how dark the machinery is. The stage key is a 54-unit
      // spot 3.6 m away — it exists to make lacquer look wet, and the chrome the model
      // ships on the arms took the whole of it: the arm standing beside the boy rendered
      // as a featureless white slab with light strips on it, brighter than the armour it
      // was building (shots/suitup/S_mk1_32.png, S_mk1_68.png). Machinery in every
      // reference frame of this ritual is nearly black with a highlight running down one
      // edge. Take the albedo down and the roughness up and the same lamp gives exactly
      // that, without touching the lamp that the armour needs.
      for (const m of mats) {
        if (!m || !m.color) continue;
        if (m.emissive && m.emissive.r + m.emissive.g + m.emissive.b >= 0.02) continue;
        if (!m.userData.mzDarkened) {
          m.userData.mzDarkened = true;
          // Clamp the brightest channel rather than scaling everything down, so the
          // amber hazard trim keeps its hue instead of turning into another grey.
          // 0.28 was still cream-white under an 82-unit key a metre away: the arm nearest
          // the camera in shots/suitup/S_mk3_50.png reads as pale plastic and pulls the
          // eye off the armour. Machinery in the reference is nearly black with one hot
          // edge, so the ceiling is lower and the surface rougher than anything the
          // modeller would author for a part meant to be seen on its own.
          const peak = Math.max(m.color.r, m.color.g, m.color.b);
          if (peak > 0.16) m.color.multiplyScalar(0.16 / peak);
          if (m.roughness !== undefined) m.roughness = Math.min(1, Math.max(m.roughness, 0.62));
        }
      }
      o.castShadow = true;
      o.receiveShadow = true;
    });

    // Static half: pit and hatches stay where the model put them.
    if (proto) proto.parent && proto.parent.remove(proto);
    this.group.add(src);

    // Four arms around the pad. Two forward, two back, off to the sides so nothing
    // reaches through the body. Alternating heights so the silhouette is not a row.
    // Close enough that one arm can cross the body and still reach the far shoulder
    // (reach is L1+L2 = 1.61 m from a shoulder that now stands 0.95 m up), far enough
    // that the mast is never inside him.
    const layout = [
      { pos: [0.92, 0, 0.86], seed: 0 },
      { pos: [-0.92, 0, 0.86], seed: 1 },
      { pos: [1.00, 0, -0.80], seed: 2 },
      { pos: [-1.00, 0, -0.80], seed: 3 },
    ];
    for (let i = 0; i < layout.length; i++) {
      const clone = proto ? proto.clone(true) : new THREE.Group();
      clone.name = 'arm' + i;
      const holder = new THREE.Group();
      holder.name = 'armholder' + i;
      holder.position.set(layout[i].pos[0], -RISE, layout[i].pos[2]);   // stowed; see _applyRise
      holder.add(clone);
      this.group.add(holder);
      const rootNode = clone.getObjectByName('piv_arm_root') || clone;
      const arm = new Arm(rootNode, i);
      arm.holder = holder;
      arm.home = new THREE.Vector3(layout[i].pos[0], 0, layout[i].pos[2]);
      arm.fold();
      this.arms.push(arm);
    }
    this.setDeploy(0);
  }

  setOrigin(pos, yaw = 0) {
    this.group.position.copy(pos);
    // A hair above the floor. The hatch halves are flat plates at y=0 and the workshop
    // floor is also a flat plate at y=0; coplanar at 91 m from the camera they z-fight
    // into a shimmering chequerboard.
    this.group.position.y += 0.012;
    this.group.rotation.set(0, yaw, 0);
  }

  setVisible(v) { this.group.visible = v; }

  // 0 = floor closed, arms in the pit. 1 = floor open, arms up at working height.
  setDeploy(t) {
    this.deployT = THREE.MathUtils.clamp(t, 0, 1);
    // hatches lead, arms follow: the floor is fully open by t=0.55
    const hatch = THREE.MathUtils.smoothstep(this.deployT, 0.0, 0.55);
    const rise = THREE.MathUtils.smoothstep(this.deployT, 0.30, 1.0);
    if (this.hatchL) this.hatchL.position.x = 1.55 + HATCH_SLIDE * hatch;
    if (this.hatchR) this.hatchR.position.x = -1.55 - HATCH_SLIDE * hatch;
    this._rise = rise;
    this._applyRise();
    this.group.visible = this.deployT > 0.001;
  }

  // How far each arm individually stands out of the pit, 0..1, multiplied by the
  // deploy. The Mk I is built by ONE arm, and with all four up the other three stood
  // around the boy doing nothing while the working one was hidden behind them — three
  // idle machines is not a cave, it is a car factory (shots/suitup/S_mk1_32.png). An
  // arm a sequence is not using stays down in the pit where it cannot be seen.
  setArmRaise(index, v) {
    this.armRaise[index] = THREE.MathUtils.clamp(v, 0, 1);
    this._applyRise();
  }

  setArmsRaised(list) {
    for (let i = 0; i < this.arms.length; i++) this.armRaise[i] = list.includes(i) ? 1 : 0;
    this._applyRise();
  }

  _applyRise() {
    const rise = this._rise || 0;
    for (const a of this.arms) {
      const k = rise * (this.armRaise[a.index] !== undefined ? this.armRaise[a.index] : 1);
      a.holder.position.y = ARM_STAND - (RISE + ARM_STAND) * (1 - k);
    }
  }

  // Which arm should serve a plate: the closest free one, so two arms working on the
  // left and right of the body do not cross over each other.
  pickArm(worldPos, busy) {
    let best = null, bestD = Infinity;
    for (const a of this.arms) {
      if (busy && busy.has(a.index)) continue;
      const d = a.root.getWorldPosition(_v).distanceTo(worldPos);
      if (d < bestD) { bestD = d; best = a; }
    }
    return best || this.arms[0];
  }

  update() { /* driven entirely by the sequences */ }

  dispose() {
    this.group.parent && this.group.parent.remove(this.group);
  }
}

// A stand-in used only if models/gantry.glb has not been generated. Same node names,
// same proportions, so the sequences behave identically.
function buildFallbackGantry() {
  const dark = new THREE.MeshStandardMaterial({ color: 0x0e1013, metalness: 0.9, roughness: 0.45 });
  const chrome = new THREE.MeshStandardMaterial({ color: 0x9aa0a6, metalness: 1, roughness: 0.18 });
  const root = new THREE.Group();
  root.name = 'gantry_root';
  const mk = (name, parent, pos) => {
    const o = new THREE.Object3D(); o.name = name;
    o.position.set(pos[0], pos[1], pos[2]); parent.add(o); return o;
  };
  const bar = (w, h, d, mat) => new THREE.Mesh(new THREE.BoxGeometry(w, h, d), mat);
  for (const [n, sx] of [['hatchL', 1], ['hatchR', -1]]) {
    const m = bar(1.55, 0.06, 3.7, dark);
    m.name = n; m.position.set(sx * 1.55 - sx * 0.775, -0.03, 0);
    const holder = new THREE.Group(); holder.name = n;
    holder.position.set(sx * 1.55, 0, 0);
    m.position.set(-sx * 0.775, -0.03, 0); m.name = n + '_mesh';
    holder.add(m); root.add(holder);
  }
  const proto = new THREE.Group(); proto.name = 'arm_proto';
  const pr = mk('piv_arm_root', proto, [0, 0, 0]);
  const mast = new THREE.Mesh(new THREE.CylinderGeometry(0.115, 0.115, 2.07, 16), dark);
  mast.position.y = -0.415; pr.add(mast);
  const yaw = mk('piv_arm_yaw', pr, [0, 0.62, 0]);
  const sh = mk('piv_arm_shoulder', yaw, [0, 0.10, 0]);
  const up = new THREE.Mesh(new THREE.CylinderGeometry(0.085, 0.085, 0.78, 14), dark);
  up.position.y = 0.39; sh.add(up);
  const el = mk('piv_arm_elbow', sh, [0, 0.78, 0]);
  const fo = new THREE.Mesh(new THREE.CylinderGeometry(0.062, 0.062, 0.62, 12), dark);
  fo.position.y = 0.31; el.add(fo);
  const wr = mk('piv_arm_wrist', el, [0, 0.62, 0]);
  for (const [n, sx] of [['piv_arm_jawL', 1], ['piv_arm_jawR', -1]]) {
    const j = mk(n, wr, [sx * 0.055, 0.055, 0]);
    const f = bar(0.05, 0.17, 0.075, chrome); f.position.set(sx * 0.028, 0.085, 0); j.add(f);
  }
  mk('piv_arm_grip', wr, [0, 0.21, 0]);
  root.add(proto);
  console.warn('[gantry] models/gantry.glb not found — using the procedural stand-in');
  return root;
}
